[build]
    publish = "public"
    command = "npm run build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[build.environment]
    NODE_VERSION = "16"

# Enable CORS headers
[[headers]]
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"